version: '3.1'

services:

  logz-app:
    image: krkr/logz
    environment:
      - LOGZ_URL=http://logz-es:9200
    deploy:
      labels:
        - ServiceSha1=$SHA1
        - traefik.port=4242
        - traefik.frontend.rule=Host:logz.$ONS_ZONE
        - service={"name":"logz-app","checks":[ "check-http 200 https://logz.your.domain/s/" ]}

  logz-es:
    image: krkr/es
    volumes:
      - /home/ubuntu/data/logz-es:/usr/share/elasticsearch/data
    deploy:
      labels:
        - ServiceSha1=$SHA1
        - traefik.port=9200
        - traefik.frontend.rule=Host:logz-es.n1.$ONS_ZONE
        - traefik.frontend.auth.basic=admin:$apr1$.FKMdR9e$V4Vgl9L5IX7ZzPhZJjNFI1
        - service={"name":"logz-es","checks":[ "check-http 401 https://logz-es.n1.your.domain" ]}
      placement:
        constraints:
          - node.hostname == n1

networks:
  default:
    external:
      name: c1_traefik